version: "3" #docker-compose版本，这里的3不要动
services:
   db: # 数据库的镜像信息
     image: mysql:5.7 # 使用mysql:5.7的镜像
     volumes: # 数据库文件存放在宿主机的`~/data/mysql`位置，如果宿主机目录不存在，则会自动创建
       - /data/data/mysql:/var/lib/mysql # 如果启动失败，则总是会重启。因为镜像有依赖的情况，不停重启可以保证依赖项启动成功后自己再运行
     restart: always
     environment: # 指定root密码为`tank123`，并且创建一个新数据库`tank`，同时用户名和密码为`tank` `tank123`
       MYSQL_ROOT_PASSWORD: tank123
       MYSQL_DATABASE: tank
       MYSQL_USER: tank
       MYSQL_PASSWORD: tank123
   tank: # 依赖 mysql:5.7 的镜像
     image: eyeblue/tank # 蓝眼云盘的镜像信息
     depends_on:
       - db
     ports:  # 端口映射关系，宿主机端口:镜像端口
       - "6010:6010"  # 如果启动失败，则总是会重启。因为镜像有依赖的情况，不停重启可以保证依赖项启动成功后自己再运行
     restart: always
     environment:  # mysql的端口
       TANK_MYSQL_PORT: 3306 # Mysql的主机，和services的第一个节点一致。
       TANK_MYSQL_HOST: db  # 数据库
       TANK_MYSQL_SCHEMA: tank  # 数据库的用户名
       TANK_MYSQL_USERNAME: tank  # 数据库的密码
       TANK_MYSQL_PASSWORD: tank123  # 超级管理员的昵称。只能是英文或数字
       TANK_ADMIN_USERNAME: admin # 超级管理员邮箱，作为登录账号
       TANK_ADMIN_EMAIL: admin@tank.eyeblue.cn  # 超级管理员密码，作为登录密码
       TANK_ADMIN_PASSWORD: 123456
     volumes: # 日志文件存放在宿主机的`~/data/tank/log`位置，如果宿主机目录不存在，则会自动创建
       - /data/data/tank/log:/data/log # 上传文件存放在宿主机的`~/data/tank/matter`位置，如果宿主机目录不存在，则会自动创建
       - /data/data/tank/matter:/data/matter
